### ISSUE TITLE
Double Whispers

### ISSUE THREAD

**Issue by Nihlo** [Gogo1951/GogoWatch#19] opened 2021-09-26 17:53 UTC
Some downranks trigger double-whispers, like Shield and Aspekt of the Hawk:

![gogo](https://user-images.githubusercontent.com/26931653/134818683-82d54de5-a849-4968-8b79-cbd9202f1ec4.jpg)

**Comment by Gogo1951** [comment] 2021-10-16 04:47
Dupe of #10

**Closed by Gogo1951** 2021-10-16 04:47 UTC
